[project]
name = "ohtm-dash"
version = "0.3.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dash~=3.4.0",
    "dash-bootstrap-components~=2.0.4",
    "seaborn~=0.13.2",
]

[dependency-groups]
prod = [
    "gunicorn~=25.0.1",
]
