[project]
name = "ohtm-dash"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dash>=3.0.2",
    "dash-bootstrap-components>=2.0.0",
    "seaborn>=0.13.2",
]

[dependency-groups]
prod = [
    "gunicorn>=23.0.0",
]
